M48
; DRILL file {KiCad (6.0.10)} date Sun Jan  8 15:35:17 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-08T15:35:17+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X105.0Y-105.0
X105.0Y-145.0
X195.0Y-105.0
X195.0Y-145.0
T0
M30
